### ISSUE TITLE
Structure project

### ISSUE THREAD

**Issue by filipefilardi** [nagoya-foundation/r-functions-performance#4]
Structure src folder to be scalable

**Comment by filipefilardi** [comment]
Maybe something like this

```
r-functions-performance/
├── results/
│	└──performance_[function].md
└── src/
 	├── parser/
 	│	├── fill_readme.py|.R
	│	└── find_winner.py|.R
	├── performance/
	│	└── analyse_[function].R
	└── utils/
		└── to_markdown.R
```

**Comment by filipefilardi** [comment]
This will also solve this issue #6

**Comment by blmayer** [comment]
I think inside the src folder we should have only the performance-[function], maybe with a different name, any auxiliary file, like to_markdown, and a main.R to run it all. So other files like find_winner and fill_readme would be inside the tools folder in the parent directory. These are my thoughts at the moment.

**Comment by filipefilardi** [comment]
I like this idea, let's do it

**Comment by filipefilardi** [comment]
Solved in [commit](https://github.com/nagoya-foundation/r-functions-performance/commit/44b699a335fae8454bb14fd2bc32aba2612c8eec)

I changed **aux.R** to **to_markdown.R**, i think is better to have many R function inside tools folder instead of **tools/aux.R** with all function inside aux.R, making it more intuitive and easier to mantain
