### ISSUE TITLE
Choose a better dataset

### ISSUE THREAD

**Issue by filipefilardi** [nagoya-foundation/r-functions-performance#7]
Need a new dataset.

### Conditions
1. Not large enough to make it painfull to call functions 1000 times over it;
2. Not small enough to make size irrelevant;
3. Cannot be related to anything controversial, need to be something neutral;
4. Cannot be perfect, we need to simulate real life function calls (data missing and other stuff...);
5. Need to have a path, so we can give credits to the owner.

**Comment by tramontini** [comment]
Maybe this one? https://www.kaggle.com/jameslko/gun-violence-data/data

**Comment by tramontini** [comment]
What would be a large dataset? 3MB or more?

**Comment by KKulma** [comment]
would you consider any R's in-built datasets?

**Comment by filipefilardi** [comment]
Sure, the dataset must follows the conditions said above tho :smiley:
